### PR TITLE
Remove unneeded options in shoppingcart.proto

### PR DESCRIPTION
**Pull request by vkorenev**
See also cloudstateio/samples-ui-shoppingcart#12

### CODE REVIEW

**Comment by vkorenev** [comment]
@coreyauger

**Comment by hseeberger** [comment]
@vkorenev, the "unneeded options" are for the HTTP transcoding. Have you verified, e.g. by using cURL, that calling the exposed HTTP API behaves like expected/before after removing the "unneeded options"?

**Comment by vkorenev** [comment]
@hseeberger, I have verified that the shopping cart UI works well with the persistent entity. However, I have not tried to invoke the service with grpcurl. I'll check that.

**Comment by vkorenev** [comment]
@hseeberger, you are right. `body: "*"` is needed there for HTTP transcoding. I reverted that change back.
The rest can be removed safely.

**Pull request closed without merging**
